### ISSUE TITLE
Footerlink not relative

### ISSUE THREAD

**Issue by wasmitinternet** [christopherkurth/TwentyFifteenSE#1]
In the footer.php a link to "Impressum & Datenschutz" is not relative to the domain. In addition, the pages must be separated.

**Comment by christopherkurth** [comment]
Erste Anpassung eingepflegt [https://github.com/christopherkurth/TwentyFifteenSE/commit/75dd0cb0eebab88a0ba8a6a92a2b4557d9c3ed20](https://github.com/christopherkurth/TwentyFifteenSE/commit/75dd0cb0eebab88a0ba8a6a92a2b4557d9c3ed20) als nächstes setze ich mich an die Customizer Integration.
